config/routes.rb
Rails.application.routes.draw do
  
  
  root :to => 'tops#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resources :users, only: [:show,:edit, :update, :unsubscribe, :withdraw] do
    collection do
      # 退会確認画面
      get "unsubscribe", :to => 'users#unsubscribe'
     # 論理削除用のルーティング
      patch "withdraw", :to => 'users#withdraw'
    end
  end

  post '/tops/guest_sign_in', to: 'tops#guest_sign_in'
 
 resources :posts do
   resource :favorites, only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
end
get "search" => "searches#search"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  validate :verify_file_type
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  enum sex: { man: 0, woman: 1 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   # is_validがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_valid == true)
  end
  private

  def verify_file_type
    return unless image.attached?
  
    allowed_file_types = %w[image/jpg image/jpeg image/gif image/png]
    unless allowed_file_types.include?(image.blob.content_type)
      errors.add(:image, 'はJPEG、GIF、PNG形式の画像を選択してください')
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sig
  # GET /resource/edit
  # def edit
  #   super
  # end
  def create
    super
  end
  # PUT /resource
   def update
    super
   end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  def after_sign_up_path_for(resource)
    posts_path
  end
  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
 
 def configure_sign_up_params
     devise_parameter_sanitizer.permit(
       :sign_up, keys: [ :name, :sex, :introduction, :career, :good_place,  :email, :password, :password_confirmation, :prefecture_id ])
 end

  def configure_account_update_params
     devise_parameter_sanitizer.permit(
       :account_update, keys: [ :name, :sex, :introduction, :career, :good_place,  :email, :password, :password_confirmation, :prefecture_id ])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
   #before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(user)
     posts_path
  end
 
   def after_sign_out_path_for(user)
     root_path
   end

  protected
  
   # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(
       :sign_in, keys: [ :email, :password, :password_confirmation ])
   end
   # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_user
    @user = User.find_by(name: params[:user][:name])
    if @user 
      if @user.valid_password?(params[:user][:password]) && (@user.is_valid== false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration
      else
        flash[:notice] = "項目を入力してください"
      
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    PER = 6
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(PER)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_without_password(user_params)
    redirect_to user_url
  end

  def mypage
  end
  
  def withdraw
    @user = User.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_valid: false)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to new_user_registration_path
  end
 private
  
  
  def user_params
     params.permit(:name, :sex, :introduction, :career, :good_place,  :email, :password, :password_confirmation, :prefecture_id, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="show-user-edit">
  <div class ="container">
    <div class="border-bottom text-center pt-3">
      <h2 >プロフィール編集</h2>
    </div>

    <div class="row justify-content-center mt-3">
    <%= form_with url: user_path, local: true, method: :put do |f| %>
      <div class="edit-form">
        <label for="form1" class="edit-form-label">名前</label><br>
        <%= f.text_field :name,size: 30, value: @user.name %>
      </div>
      <div class="edit-form mt-1">
        <label for="form2" class="edit-form-label">メールアドレス</label><br>
        <%= f.email_field :email, size: 30, value: @user.email %><br>
      </div>
      <div class="edit-form mt-1">
        <label for="form3" class="edit-form-label">働いてる地域</label><br>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name ) %>
      </div>
      <div class="edit-form mt-1">
        <label for="form3" class="edit-form-label">性別</label><br>
        <%= f.select :sex, User.enum_options_for_select(:sex) %>
      </div>
      <div class="edit-form mt-1">
        <label for="form4" class="edit-form-label">自己紹介</label><br>
        <%=f.text_area :introduction, size: " 30 x 5", autofocus: "true", value: @user.introduction %>
      </div>
        <div class="edit-form mt-1">
        <label for="form5" class="edit-form-label">性別</label><br>
      </div>
      <div class="edit-form">
        <%= f.label :image,"写真"%>
        <%= f.file_field :image %>
      </div>
      <div class="edit-form-bottan">
            <%= f.submit '保存' %>
      </div>
    <% end %>
    </div>
      <%= link_to unsubscribe_users_path do %>
      <h3 class="edit-withdrawal">退会する</h3>
      <% end %>
  </div>
</div>

app/views/users/mypage.html.erb
<h1>マイページ</h1>
 <% if @user.image.attached? %>
  <p>
    <strong><%= User.human_attribute_name("沖縄") %>:</strong>
    <%= image_tag @user.image %>
  </p>
 <% end %>

     <div class="d-flex align-items-center">
      <%= link_to mypage_edit_users_path do %>
        <h1>プロフィール編集</h1>
      <% end %>
    </div>

          

app/views/users/show.html.erb
<div class=" user-show-image">
  <div class="user-show">
     <% if @user.image.attached? %>
      <%= image_tag @user.image, class: "icon-mini"%>
      <% else %>
      <p>No image available</p>
     <% end %>   
     
   <div class="user-show-text">
     <h2><%= @user.name %></h2><br>
      <div class="user-show-text2">
       <%= @user.human_attribute_enum(:sex)%>
      </div><br>
      <div class="user-show-text2">
       <%= @user.prefecture.name%>
      </div><br>
      <P class="user-show-text2"><%= @user.introduction %></P>
   </div>
   <div class="user-show--purofiru">
      <% if current_user.present? %>
        <% if current_user.id == @user.id %>
          <%= link_to "プロフィール編集", "#{@user.id}/edit" %>
        <% end %>
      <% end %>
   </div>
  </div>
</div>

<div class="contener m-0">
 
 <div class="show-user-index">
   <% @posts.each do |post| %>
    <div class="show-user-article"> 
     <div>
      <i class="fa-solid fa-location-pin"></i><%= post.post_place %>
     </div>
     <% if post.post_images.attached? %>
      <% post.post_images.each do |image| %>
       <%= image_tag image, size: '400x300' %>
      <% end %>
     <% end %><br>
     <span>タイトル：<%= link_to post.title, post_path(post)%><span>
     <br>
     <div class="mb-2">
      <%= post.post_content.truncate(70)%>
     </div>
    </div>
   <% end %>
 </div>
</div>
 <div class="d-flex justify-content-end">
 <%= paginate @posts%>
 </div>

app/views/users/unsubscribe.html.erb
<h2>退会お手続き</h2>
 <p>
   退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
   再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
   本当に退会してよろしいですか？
 </p>
  <%= link_to "退会する", withdraw_users_path, method: :patch, data: { confilm: "本当に退会しますか？" } %>
  <%= link_to "退会しない", mypage_users_path(current_user) %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>