config/routes.rb
Rails.application.routes.draw do
  
  
  root :to => 'tops#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resources :users, only: [:show,:edit, :update, :unsubscribe, :withdraw] do
    collection do
      # 退会確認画面
      get "unsubscribe", :to => 'users#unsubscribe'
     # 論理削除用のルーティング
      patch "withdraw", :to => 'users#withdraw'
    end
  end

  post '/tops/guest_sign_in', to: 'tops#guest_sign_in'
 
 resources :posts do
   resource :favorites, only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
end
get "search" => "searches#search"
  
end

app/models/post.rb
class Post < ApplicationRecord
     belongs_to :user
     has_many_attached :post_images
     has_many :favorites, dependent: :destroy
     has_many :comments, dependent: :destroy
     def favorited_by?(user_id)
      favorites.exists?(user_id: user.id)
     end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    PER = 6
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(PER)
# 投稿順(最新順)にデータを表示させるようにする
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments  #投稿詳細に関連付けてあるコメントを全取得
    @comment = Comment.new
  end
  
  def new
    @post = Post.new
# 空のpostインスタンスを生成する
  end

  def edit
      @post = Post.find(params[:id])
  end

  def create
   @post = Post.new(post_params)
# newページで入力した内容が格納された状態のインスタンスが飛んでくる
   @post.user_id = current_user.id
# user_idカラムにcurrent_userのidを代入する
   if @post.save
    redirect_to posts_path
   else
    render 'new'
   end
  end
  

  def update
      @post = Post.find(params[:id])
# 編集ページの送信ボタンから飛んできたときのparamsに格納されたidを元に、該当する投稿データを探して、変数に代入する
  if @post.update(post_params)
    redirect_to post_path, notice: "投稿を編集しました"
  else
    flash.now[:danger] = "編集に失敗しました"
    render 'edit'
  end
  end

  def destroy
      @post = Post.find(params[:id])
  # 削除リンクから飛んできたときのparamsに格納されたidを元に、該当する投稿データを探して、変数に代入する
    if @post.destroy
      redirect_to posts_path, notice: "アウトプットを削除しました"
    else
      flash.now[:danger] = "削除に失敗しました"
      render 'show'
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :post_content,:keyword,:post_place, post_images:[] )
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="new-post">
  <div class="contener">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">新しい思い出</h2>
    </div>
    
    <div class="row justify-content-center">
      <%= form_with model: @post do |f|%>
      
      <div class="form-group">
        <label class="form-label">タイトル</label>
        <%= f.text_field :title, class: "form-control"%>
      </div>
      
      <div class="form-group">
        <label class="form-label">場所</label>
        <%= f.text_field :post_place, class: "form-control"%>
      </div>

      <div class="form-group">
        <label class="form-label">感想</label>
        <%= f.text_area :post_content, rows: 10, class: "form-control", style: "width:100% high:100%"%>
      </div>
      <br>
      <div class="form-group">
        <label class="form-label">画像</label></br>
        <%= f.file_field :post_images, multiple: true %>
      </div>
      </br>
      <div class="submit"> 
        <%= f.submit "投稿する", class: "btn btn-success"%>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row justify-content-center">
   <h1 class="font-weight-normal mt-3">旅行投稿一覧</h1>
</div>


 
 <div class="post-index">
   <% @posts.each do |post| %>
    <div class=" post-article"> 
     <div class ="post-article-name">
       <div>
         <i class="fa-solid fa-location-pin"></i><%= post.post_place %>
       </div> 
       <div>
         @<%= link_to post.user.name, "users/#{post.user.id}" %>
       </div>
     </div>
     <% if post.post_images.attached? %>
       <% post.post_images.each do |image| %>
        <%= image_tag image, size: '330x250' %>
       <% end %>
     <% end %><br>
     <span>タイトル:<%= link_to post.title, post_path(post.id) %></span>
     <br>
     <%= post.post_content.truncate(34) %>
    </div>
   <% end %>
 </div>

 <div class="d-flex justify-content-end">
   <%= paginate @posts%>
 </div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="show-cover">
  <div class="container">
 
    <div class="post-show ">
      <div class="">
        <% if @post.post_images.attached? %>
          <% @post.post_images.each do |image| %>
          <%= image_tag image, class: "w-100 show-post-img" %>
          <% end %>
        <% end %>
      </div>
      
      <div class="post-show-center">
        <h2 class="">
          <%= @post.title %>
        </h2>
        <div class="post-show-center-text">
          <%= @post.post_content %>
        </div>
        <%= form_with model:[@post, @comment],class: "post-show-form", local: false do |f| %>
          <%= f.text_area :comment_content, rows:'3',placeholder: "コメント", class:"post-show-center-coment"  %>
          <%= f.submit "送信", class: "post-show-button" %>
        <% end %>
      </div>
      
      <div class="post-show-center-icon">
        <% if current_user == @post.user%>
          <%= link_to "/posts/#{@post.id}/edit" do %>
            <i class="fa-regular fa-pen-to-square fa-size" style="color: #111722;"></i>
          <% end %>
          <%= link_to"/posts/#{@post.id}", method: :delete do %>
            <i class="fa-regular fa-trash-can fa-size" style="color: #e52a33;"></i>
          <% end %>
        <% end %>
      </div>
    </div>
      <h3 class="post-show-comment">コメント一覧
        <% if @post.favorited_by?(current_user) %>
          <%= link_to post_favorites_path(@post.id), method: :delete do %>
            <span>❤︎</span>
          <% end %>
          <% else %>
          <%= link_to post_favorites_path(@post.id), method: :post do %>
            <span class="color-red">♡お気に入りする</span>
          <% end %>
          <% end %>
      </h3>
        <% @comments.each do |comment| %><br>
          <%= comment.user.name %>
          <span class="comment-space"><%=comment.comment_content %></span>
          <% if current_user.id == comment.user_id %>
            <%= link_to post_comment_path(@post.id, comment.id), method: :delete do %>
              <span class="comment-space">コメント削除</span>
            <% end %>
          <% end %>
        <% end %>
  </div>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>