config/routes.rb
Rails.application.routes.draw do
  
  
  root :to => 'tops#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resources :users, only: [:show,:edit, :update, :unsubscribe, :withdraw] do
    collection do
      # 退会確認画面
      get "unsubscribe", :to => 'users#unsubscribe'
     # 論理削除用のルーティング
      patch "withdraw", :to => 'users#withdraw'
    end
  end

  post '/tops/guest_sign_in', to: 'tops#guest_sign_in'
 
 resources :posts do
   resource :favorites, only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
end
get "search" => "searches#search"
  
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm samuraimart-header-container">
    <%= link_to root_path do %>
      <%= image_tag "/images/resort_work.png", size: "80x80" %>
    <% end %>
    
    <div class="form-inline">
      <% if user_signed_in? %>
        <%= form_with url: search_path, local: true, method: :get do |form| %>
          <%= form.text_field :keyword %>
          <%= form.submit "検索" %>
        <% end %>
      <% end %>
    </div>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto mr-2 mt-2">
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %>
        <li class="nav-item mr-3">
        <%= link_to posts_path, class: "dropdown-item" do %>
            <label>home</label>
          <% end %>
        <li class="nav-item mr-3">
          <% if user_signed_in? %>
           <%= link_to "投稿", new_post_path, class: "dropdown-item" %>
          <% end %>
        <li class="nav-item mr-3">
          <%= link_to  "/users/#{current_user.id}", class: "dropdown-item" do %>
            <label>マイページ</label>
          <% end %>
        </li>
        
        </li>
        <li class="nav-item mr-3">
          <%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item" %>
        </li>
      <% else %>
        <li class="nav-item mr-5">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <label>新規登録</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %>
            <label>ログイン</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to tops_guest_sign_in_path, method: :post, class: "nav-link" do %>
            <label>ゲストログイン（閲覧用）</label>
          <% end %>
        </li>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResortWork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-visit-control" content="reload">
    
    <script src="https://kit.fontawesome.com/f99782d83f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% unless current_page?(root_path) %>
     <%= render partial: 'layouts/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>